### ISSUE TITLE
Boundary Conditions

### ISSUE THREAD

**Issue by jejjohnson** [dionhaefner/shallow-water#2]
Hi, I was looking at the code and was attempted to reproduce it. I was wondering could you tell me what the boundary conditions are? I see it in code ([here](https://github.com/dionhaefner/shallow-water/blob/master/shallow_water_nonlinear.py#L118)) but I don't know what they physically represent nor do I understand why they are put in the interior points of the arrays.

- boundary values of h must not be used
h[0, :] = h[-1, :] = h[:, 0] = h[:, -1] = np.nan
- u boundary
arr[:, -2] = 0.
- v boundary
arr[-2, :] = 0.

is this some sort of free-slip (zero-derivative) boundaries for the North and East?

—-

Im thinking in terms of the Arakawa C-Grid whereby we have:
* `h = [Nx, Ny]` - center of cell
* `u = [Nx+1, Ny]` - left/right face of cell
* `v = [Nx, Ny+1]` - top/down face of cell

But I see here that you've put everything on the same array shape. If it were the Arakawa C-Grid style, what would be the boundary conditions for u and v?

**Comment by dionhaefner** [comment]
This *is* an Arakawa C-grid, just with additional padding to make everything the same shape.

`u[:, -2]` is located on the eastern boundary, so we must set it to 0 if the domain isn't periodic (no normal flow into the boundary). Analogous for `v` on the northern boundary.

Your remark that `u` and `v` should be larger than `h` is correct. `u[:, 0]` is technically part of the domain (it is not for `h` and `v`). We don't need to touch that value though since we never update it, except during the boundary exchange for a periodic boundary. So for non-periodic BCs it will stay 0 forever, which is again the no-normal flow BC.

There's some more complexity to this though. For example, this line ensures that the derivative of `h` is zero at the domain edge:

https://github.com/dionhaefner/shallow-water/blob/883fad95e0e20a653f595fb484b3245851f4e8cf/shallow_water_nonlinear.py#L154

Then there are cases where `u` and `v` are interpolated to cell centers or other edges:

https://github.com/dionhaefner/shallow-water/blob/883fad95e0e20a653f595fb484b3245851f4e8cf/shallow_water_nonlinear.py#L168

Since the velocities are padded with zeros this implies a linear gradient across the interface, so yea it's some sort of free slip, but not zero-derivative (zero vorticity maybe?).

**Comment by jejjohnson** [comment]
Ah, I see now. I did figure it was some sort of Arakawa C grid structure. So an analogous way without the special padding already preallocated would be something like

```python
# incoming fields on Arakawa C-grid
h: Array["Nx Ny"] = ...
u: Array["Nx+1 Ny"] = ...
v: Array["Nx Ny+1"] = ..

# pad the h domain with edge points
# explanation: ensure zero derivatives for h
h: Array["Nx+2 Ny+2"] = pad(h, pad_width=((1,1),(1,1)), mode="edge")

# enforce boundaries on u and v, tangential velocity is zero
# explanation: no-slip boundaries for east and north wall
u[-1,:] = 0.0
v[:,-1] = 0.0

# pad the velocities with zeros
# explanation: ensure zero derivatives for nodes, i.e., vorticity
u: Array["Nx+3 Ny+2"] = pad(u, pad_width=((1,1),(1,1)), mode="constant", constant_values=0.0)
v: Array["Nx+2 Ny+3"] = pad(v, pad_width=((1,1),(1,1)), mode="constant", constant_values=0.0)

# continue with right hand side calculations
h_rhs: Array["Nx Ny"] = ...
u_rhs: Array["Nx+1 Ny"] = ...
v_rhs: Array["Nx Ny+1"] = ...
```

Does this look correct?


--- 
 For context, I am creating a library  ([`finitevolx`](https://github.com/jejjohnson/finitevolX/tree/main))with some simple finite volume tools that I'll need for my research with simple ocean models ([`somax`](https://github.com/jejjohnson/somax)).  

Your example is the canonical example on the internet so I wanted to test out the API for this example. I also wanted it to be a bit more didactic where every step is explained a bit more (The optimization can come later). The linear model works for the [simple case](https://github.com/jejjohnson/finitevolX/blob/ex-swm/scripts/swm_linear.py) but the linear model (and of course nonlinear) case for the more [complex case](https://github.com/jejjohnson/finitevolX/blob/ex-swm/scripts/swm.py) does not currently work. So I wanted to make sure I fully understand the conditions you're simulating.

**Comment by dionhaefner** [comment]
Yes this would probably work, but I would recommend making all arrays the same shape which simplifies the stencils a lot (for example, `dydx = (y[2:, 1:-1] - y[1:-1, 1:-1]) / dx` independent of which grid `y` is on). So you'd have different paddings for `u` and `v`.

I'm sure you've looked at [JAX-cfd](https://github.com/google/jax-cfd); I really like how they define array data structures that are aware of the grid they're on so you don't even need to write explicit stencils.

BTW, [here](https://github.com/mpi4jax/mpi4jax/blob/master/examples/shallow_water.py) is a version of this repo with JAX + MPI (works even on multi-GPU). Might come in handy.

**Comment by jejjohnson** [comment]
It definitely makes sense to keep everything on the same grid. I also appreciate the higher level API that `jax-cfd` has. I am working on something similar with the [`fieldx`](https://github.com/jejjohnson/fieldx) and [`somax`](https://github.com/jejjohnson/somax/tree/main) package I mentioned. I think my package is catering more towards scientists/researchers. I've had a lot of trouble with domain-expert collaborators who aren't the best programmers adopting stuff like `jax-cdf`. So I'm going more for readability rather than optimization or automization with these tools. I'm hoping also that the codes I build will be easily translated to more optimized/automated stuff, i.e., anything I code here can easily be translated to something better like `jax-cfd`.

In any cases, thanks for your help! I think I have it working now ([linear](https://github.com/jejjohnson/finitevolX/blob/main/scripts/swm_linear.py) & [nonlinear](https://github.com/jejjohnson/finitevolX/blob/main/scripts/swm.py))(more or less). I still have some stability issues for longer simulations but the basics work for now.

I'll also take a look at the [`mpi/swm`](https://github.com/mpi4jax/mpi4jax/blob/master/examples/shallow_water.py) example you have. It'll definitely come in handy!
